/** Generated by scripts/optimize-images.mjs — keep WIDTHS in sync with the script. */
export const PORTRAIT = {
  width: 2688,
  height: 2819,
  widths: [320, 480, 640, 800, 1080, 1440],
  basePath: "/images/generated/portrait",
  halo: "/images/generated/portrait-halo.webp",
  rim: "/images/generated/portrait-rim.webp",
} as const;
