/** Generated by scripts/optimize-images.mjs — keep WIDTHS in sync with the script. */
export const PORTRAIT = {
  width: 846,
  height: 862,
  widths: [320, 480, 640, 800],
  basePath: "/images/generated/portrait",
  halo: "/images/generated/portrait-halo.webp",
  rim: "/images/generated/portrait-rim.webp",
} as const;
